-- Code generated by ztool. DO NOT EDIT.

local errors = {}

local function REG(name, code, message)
    errors[name] = {code = code, message = message}
end

errors.REG = REG

REG("SUCCESS", 0, "成功")
REG("SYSTEM", 1, "系统错误")
REG("CONNECTION_LIMIT", 100, "连接数超限")
REG("AUTH_FAIL", 101, "与游戏服务器认证失败")
REG("ALREADY_LOGGED", 102, "已登录")
REG("PLAYER_LOGGING_IN", 103, "玩家正在登录中, 不要重复登录")
REG("COIN_NOT_ENOUGH", 104, "金币不足")

return errors